// Task B1.2: PcmInferenceRunner slides a PCM-in chord model over the
// whole song's PCM and collects per-frame argmax predictions.
//
// The reference (test/fixtures/pcm_runner_ref.json + pcm_runner_pcm.bin)
// is generated by scripts/export/.venv/bin/python running
// chordnet_2e1d.onnx window-by-window EXACTLY as PcmInferenceRunner does
// (same 219136-sample non-overlapping window, same zero-pad + tail real-
// frame-count formula: ceil(copyLen / hopLength) where
// hopLength = windowSamples ~/ (framesPerWindow - 1)). See
// /private/tmp/.../scratchpad/gen_pcm_runner_fixture.py (not committed;
// regenerate via the same recipe if the fixture needs to change).
//
// The PCM itself is a real-audio fixture (the existing triad_cmaj hybrid_cqt
// spike fixture) tiled to ~1.75 windows (1 full window + a 3/4-window
// tail) so the test exercises both the steady-state window path and the
// zero-padded tail-drop path.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:onnxruntime/onnxruntime.dart';
import 'package:chordmind/core/model_registry.dart';
import 'package:chordmind/core/inference/pcm_runner.dart';

const _fixturesDir = 'test/fixtures';

Float32List _readF32(String path) {
  final bytes = File(path).readAsBytesSync();
  return bytes.buffer.asFloat32List(
    bytes.offsetInBytes,
    bytes.lengthInBytes ~/ 4,
  );
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUpAll(() {
    OrtEnv.instance.init();
  });

  tearDownAll(() {
    OrtEnv.instance.release();
  });

  test('rejects a non-pcm model spec', () async {
    final registry = await ModelRegistry.load();
    final ccl = registry.byName('chord_cnn_lstm');
    expect(() => PcmInferenceRunner(ccl), throwsArgumentError);
  });

  test('matches the python reference frame sequence', () async {
    final ref = jsonDecode(
      File('$_fixturesDir/pcm_runner_ref.json').readAsStringSync(),
    ) as Map<String, dynamic>;
    final pcm = _readF32('$_fixturesDir/${ref['pcm_file']}');
    expect(pcm.length, ref['total_samples']);

    final expectedClassIds = (ref['expected_class_id'] as List).cast<int>();
    final expectedHop = ref['hop_length'] as int;
    final expectedFramesPerWindow = ref['frames_per_window'] as int;

    final registry = await ModelRegistry.load();
    final spec = registry.byName('chordnet_2e1d');
    expect(spec.windowSamples, ref['window_samples']);
    expect(spec.fs, ref['fs']);

    final runner = PcmInferenceRunner(spec);
    final results = await runner.run(pcm);
    runner.dispose();

    expect(results.length, expectedClassIds.length);

    // Argmax-equal on >=99% of frames (tiny ORT drift tolerance).
    var mismatches = 0;
    for (var i = 0; i < results.length; i++) {
      if (results[i].classId != expectedClassIds[i]) mismatches++;
    }
    final matchFraction = 1 - mismatches / results.length;
    // ignore: avoid_print
    print(
      'pcm_runner argmax match: ${(matchFraction * 100).toStringAsFixed(2)}% '
      '(${results.length} frames)',
    );
    expect(matchFraction, greaterThanOrEqualTo(0.99));

    // frameIndex is 0..N-1, monotonically increasing.
    for (var i = 0; i < results.length; i++) {
      expect(results[i].frameIndex, i);
    }

    // time is monotonic increasing by the expected frame duration.
    final expectedFrameDur = expectedHop / (ref['fs'] as int);
    for (var i = 1; i < results.length; i++) {
      final dt = results[i].time - results[i - 1].time;
      expect(dt, closeTo(expectedFrameDur, 1e-9));
    }
    expect(results.first.time, 0.0);

    // No frames emitted beyond the real audio duration: the tail window
    // should have contributed strictly fewer than a full window's worth
    // of frames (it's a partial window in this fixture), and the total
    // must match the python reference's own tail-dropped count exactly.
    final fullWindowFrames = expectedFramesPerWindow; // 108
    expect(results.length, lessThan(2 * fullWindowFrames));

    // Confidence is a valid softmax-max probability.
    for (final r in results) {
      expect(r.confidence, greaterThan(0.0));
      expect(r.confidence, lessThanOrEqualTo(1.0));
    }
  });
}
